spring:
  profiles:
    default: local
  kafka:
    bootstrap-servers: "localhost:9092"
  datasource:
    url: jdbc:h2:mem:~/EnrollApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enroll?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never